image: ctornau/latex

before_script:
  - apt-get update && apt-get install -y python3 python3-dev python3-pip
  - python3 --version
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -e .[all]

testing:
  stage: test
  script:
    - flake8 --config flake8-CI.cfg
    - pytest
    - coverage report
    - coverage xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

pages:
  stage: deploy
  script:
    - python3 -m pip install .[docs]
    - python3 -m mkdocs build
    - mv site public
  artifacts:
    paths:
    - public
  only:
    - main
