image: ctornau/latex

before_script:
  - apt-get update && apt-get install -y python3 python3-dev python3-pip
  - python3 --version
  - pip3 install matplotlib
  - pip3 install pdoc3
  - pip3 install -e .

pages:
  stage: deploy
  script:
  - cd docs; bash create_doc.sh; cd ..
  - mv docs public
  - mv gallery public/
  artifacts:
    paths:
    - public
  only:
  - master
