image: "python:3.7"  #alpine:latest

before_script:
  - python --version
  - pip install matplotlib
  - pip install -q -e .

pages:
  stage: deploy
  script:
  - cd docs; bash create_doc.sh; cd ..
  - mv docs public
  - mv gallery public/
  artifacts:
    paths:
    - public
  only:
  - master
