image: ubuntu:latest

before_script:
  - apt-get update && apt-get install -y python3 python3-dev python3-pip
  - apt-get install texlive-full 
  - python --version
  - pip install matplotlib
  - pip install pdoc3
  - pip install -e .

pages:
  stage: deploy
  script:
  - cd docs; bash create_doc.sh; cd ..
  - mv docs public
  - mv gallery public/
  artifacts:
    paths:
    - public
  only:
  - master
