image: "python:3.8"  #alpine:latest

before_script:
  - apt-get install texlive-full 
  - python --version
  - pip install matplotlib
  - pip install pdoc3
  - pip install -e .

pages:
  stage: deploy
  script:
  - cd docs; bash create_doc.sh; cd ..
  - mv docs public
  - mv gallery public/
  artifacts:
    paths:
    - public
  only:
  - master
