image: ctornau/latex

before_script:
  - apt-get update && apt-get install -y python3 python3-dev python3-pip
  - python3 --version
  - pip3 install matplotlib
  - pip3 install -e .

testing:
  stage: test
  script:
    - pip3 install -q flake8 wemake-python-styleguide
    - flake8
    - pip3 install -q pytest pytest-cov pytest-rerunfailures pytest-benchmark coverage
    - pytest
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml

pages:
  stage: deploy
  script:
    - pip3 install pdoc3
    - cd docs; bash create_doc.sh; cd ..
    - mv docs public
    - mv gallery public/
  artifacts:
    paths:
    - public
  only:
    - master
