name: github pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of uv and set the python version
      uses: astral-sh/setup-uv@v6
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        uv sync --group docs
    - name: Create doc
      run: |
        uv run mkdocs gh-deploy --force
